name: Build and test CKAN UKDS images

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      ckan-major-version: "ukds-2.11"
      ckan-services-version: "2.11"
